# Archivo de secretos para Streamlit Cloud
# Unifica toda la configuración del pipeline IoT


# API Backend
API_HOST = "0.0.0.0"
API_PORT = "8000"

# Serial (Arduino USB)
USB_PORT = "/dev/ttyACM0"
USB_BAUDRATE = "9600"

# Red y escaneo
NETWORK_INTERFACE = "eth0"
SCAN_TIMEOUT = "5"

# Modbus
MODBUS_PORT = "502"
MODBUS_TIMEOUT = "3"

# Logging
LOG_LEVEL = "INFO"

# PostgreSQL local
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "iot_db"
DB_USER = "iot_user"
DB_PASSWORD = "DAms15820"

# Puedes agregar aquí cualquier otra variable que requiera el pipeline
